--- # VRS to VariantID mapping
- name: vrs
  suffix: vrs
  url: https://zenodo.org/records/15046078/files/vrs.csv?download=1
  file: vrs.csv
  header_row: 0
  skip_rows: None
  delimiter: comma
  quoting: 0
  strip_hash: 0
  md5_url:
  md5_file:
  template: >
    ClinVar VariationID ${dict.clinvar_variation_id} has the unique GA4GH Variation Representation Specification (VRS) 
    identifier ${dict.vrs_2_0_alpha_id}.
